# Generated by Django 2.1.3 on 2018-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nike',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='НикНейм'),
        ),
    ]
