# Generated by Django 2.1.3 on 2018-12-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='seq',
        ),
    ]
